async (page) => {
  const results = [];
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  const check = (condition, label) => { if (!condition) throw new Error(label); results.push(label); };
  const nav = name => page.getByRole('navigation', {name:'Editor tools'}).getByRole('button', {name, exact:true}).click();
  const canvas = () => page.getByTestId('export-canvas');
  const canvasStyle = prop => canvas().evaluate((el, p) => el.style[p], prop);
  const slider = async (name,value) => { const el=page.getByRole('slider',{name,exact:true}); await el.fill(String(value)); };
  const input = (name) => page.getByRole('spinbutton',{name,exact:true});
  await page.goto('http://127.0.0.1:3101');
  await page.getByRole('button',{name:'Try a demo',exact:true}).click();
  await canvas().waitFor();
  check(await canvasStyle('width') === '1260px', 'Demo imports at natural size plus padding');
  for (const name of ['Images','Presets','Background','Canvas','Frame','Crop','Annotate','Export','Help']) {
    await nav(name); await page.getByRole('complementary',{name:`${name} settings`}).waitFor();
    check(await page.getByRole('heading',{name,exact:true,level:1}).isVisible(), `${name} sidebar opens`);
  }
  await nav('Presets');
  await page.getByRole('button',{name:'Apply After hours preset',exact:true}).click();
  check((await canvasStyle('background')).includes('radial-gradient'), 'Preset changes canvas background');
  check(await page.getByTestId('window-header').count() === 1, 'Preset applies window header');
  await page.getByRole('button',{name:'Undo',exact:true}).click();
  check(await page.getByTestId('window-header').count() === 0, 'Undo restores prior style');
  await page.getByRole('button',{name:'Redo',exact:true}).click();
  check(await page.getByTestId('window-header').count() === 1, 'Redo restores next style');
  await page.getByRole('textbox',{name:'Style name'}).fill('Audit style');
  await page.getByRole('button',{name:'Save style',exact:true}).click();
  check(await page.getByRole('button',{name:'Audit style',exact:true}).count() === 1, 'Style saves and becomes reusable');
  await page.getByRole('button',{name:'Apply Studio preset',exact:true}).click();
  await nav('Canvas');
  for (const [ratio,w,h] of [['16:9',1200,675],['4:3',1200,900],['1:1',1200,1200],['9:16',1200,2133]]) {
    await page.getByRole('button',{name:ratio,exact:true}).click();
    check(await input('Canvas width').inputValue() === String(w) && await input('Canvas height').inputValue() === String(h), `${ratio} changes real canvas dimensions`);
  }
  await page.getByLabel('Social size').selectOption('1080x1350');
  check(await canvasStyle('height') === '1350px', 'Social-size preset applies');
  await input('Canvas width').fill('900'); await input('Canvas height').fill('650');
  await slider('Padding',40); await slider('Canvas corners',24); await slider('Image scale',85); await slider('Horizontal position',20); await slider('Vertical position',-10); await slider('Image corners',16);
  check(await canvasStyle('borderRadius') === '24px', 'Canvas corners render');
  check((await page.getByTestId('canvas-image').getAttribute('style')).includes('scale(0.85)'), 'Image scale and positions render');
  await page.getByRole('button',{name:'Reset image position'}).click();
  check(await page.getByRole('slider',{name:'Image scale',exact:true}).inputValue() === '100', 'Image control reset works');
  await nav('Frame');
  await page.getByRole('button',{name:'light',exact:true}).click();
  await slider('Shadow',50); await slider('Frame corners',20); await slider('Window scale',90); await slider('Horizontal offset',5); await slider('Vertical offset',-5);
  await page.getByRole('switch',{name:'Show border'}).check(); await slider('Border width',3); await page.getByLabel('Border color',{exact:true}).fill('#ff8800');
  check((await page.getByTestId('image-frame').getAttribute('style')).includes('3px solid rgb(255, 136, 0)'), 'Border width and color render');
  check((await page.getByTestId('image-frame').getAttribute('style')).includes('scale(0.9)'), 'Window transforms render');
  await nav('Background');
  await page.getByRole('button',{name:'Patterns',exact:true}).click();
  const patternButtons = page.getByRole('button',{name:/^Use .* background$/});
  check(await patternButtons.count() > 10, 'Pattern library is available');
  await patternButtons.first().click();
  check((await canvasStyle('background')).includes('/patterns/'), 'Pattern renders on canvas');
  await page.getByRole('textbox',{name:'Search backgrounds'}).fill('Blue');
  await page.getByRole('button',{name:'Use Blue background',exact:true}).click();
  check((await canvasStyle('background')).includes('radial-gradient'), 'Spotlight background renders');
  await page.getByRole('textbox',{name:'Search backgrounds'}).fill('');
  await page.getByLabel('Solid color',{exact:true}).fill('#123456');
  check(await canvasStyle('background') === 'rgb(18, 52, 86)', 'Custom solid background renders');
  await page.getByRole('switch',{name:'Subtle grain'}).check();
  check(await page.getByTestId('grain-overlay').count() === 1, 'Grain is a real overlay');
  await page.getByRole('switch',{name:'Subtle grain'}).uncheck();
  await page.getByRole('switch',{name:'Transparent background'}).check();
  check(await canvasStyle('background') === 'transparent', 'Transparent background renders');
  await page.getByLabel('Start',{exact:true}).fill('#112233'); await slider('Direction',90);
  check((await canvasStyle('background')).includes('90deg'), 'Custom gradient controls render');
  check(await page.getByRole('button',{name:'Suggest a style',exact:true}).isDisabled(), 'Unconfigured AI is honestly disabled');
  await nav('Annotate');
  await page.getByRole('button',{name:'Add text',exact:true}).click();
  await page.getByRole('textbox',{name:'Text 1 content'}).fill('Release ready');
  await page.getByLabel('Text 1 position',{exact:true}).selectOption('top');
  await page.getByLabel('Text 1 size',{exact:true}).selectOption('large');
  await page.getByLabel('Text 1 color',{exact:true}).fill('#eeffcc');
  check(await page.getByTestId('text-layer').textContent() === 'Release ready', 'Text content edits render');
  await page.getByRole('button',{name:'Add magnifier',exact:true}).click();
  await page.getByLabel('Magnifier 1 position',{exact:true}).selectOption('bottom-right');
  await slider('Magnification',3); await slider('Focus X',30); await slider('Focus Y',60);
  await page.getByLabel('Shape',{exact:true}).selectOption('rectangle'); await page.getByLabel('Size',{exact:true}).selectOption('small'); await page.getByLabel('Outline style',{exact:true}).selectOption('dashed');
  check((await page.getByTestId('magnifier').getAttribute('style')).includes('background-image: url('), 'Magnifier contains real zoomed image pixels');
  await nav('Crop'); await page.getByRole('button',{name:'Start cropping',exact:true}).click();
  await page.getByRole('complementary').getByRole('button',{name:'Apply crop',exact:true}).click();
  await page.getByTestId('canvas-image').waitFor();
  const croppedSize=await page.getByTestId('canvas-image').evaluate(img=>[img.naturalWidth,img.naturalHeight]);
  check(croppedSize[0] === 880 && croppedSize[1] === 592, 'Applying initial crop produces 80 percent of source, without dragging');
  await page.getByRole('button',{name:'Undo',exact:true}).click();
  check(await page.getByTestId('canvas-image').evaluate(img=>img.naturalWidth) === 1100, 'Undo restores uncropped pixels');
  await page.getByRole('button',{name:'Redo',exact:true}).click();
  await page.getByRole('button',{name:'Restore original image',exact:true}).click();
  await page.waitForFunction(() => document.querySelector('[data-testid=canvas-image]')?.naturalWidth === 1100);
  check(true, 'Restore original is lossless');
  await page.getByRole('button',{name:'Start cropping',exact:true}).click(); await page.keyboard.press('Escape');
  check(await canvas().count() === 1, 'Escape cancels cropping');
  await nav('Export');
  await page.getByRole('textbox',{name:'File name'}).fill('shotla-audit');
  await page.getByRole('button',{name:'1×',exact:true}).click();
  for(const format of ['PNG','JPEG','WEBP']) {
    await page.getByRole('button',{name:format,exact:true}).click();
    const downloadPromise=page.waitForEvent('download');
    await page.getByRole('button',{name:'Download image',exact:true}).click();
    const download=await downloadPromise; const ext=format==='JPEG'?'jpg':format.toLowerCase();
    await download.saveAs(`output/playwright/shotla-audit.${ext}`);
    check(download.suggestedFilename() === `shotla-audit.${ext}`, `${format} download succeeds with correct file name`);
  }
  await page.context().grantPermissions(['clipboard-read','clipboard-write']);
  await page.getByRole('button',{name:'Copy as PNG'}).click();
  await page.getByText('Copied to clipboard',{exact:true}).waitFor();
  check(await page.evaluate(async()=> (await navigator.clipboard.read())[0].types.includes('image/png')), 'Copy writes a PNG to the clipboard');
  await page.getByLabel('Upload screenshots').setInputFiles('output/playwright/shotla-audit.png');
  await page.getByRole('button',{name:'Select shotla-audit.png',exact:true}).waitFor();
  await nav('Presets'); await page.getByRole('button',{name:'Apply Warm editorial preset',exact:true}).click();
  await page.getByRole('button',{name:'Select Studio overview.png',exact:true}).click();
  check(await page.getByTestId('text-layer').textContent() === 'Release ready', 'Switching images preserves original annotations');
  await page.getByRole('button',{name:'Select shotla-audit.png',exact:true}).click();
  check(await page.getByTestId('text-layer').count() === 0, 'New image has independent layers');
  check(await page.getByRole('button',{name:'Apply Warm editorial preset',exact:true}).getAttribute('aria-pressed') === 'true', 'Second image retains independent styling');
  await page.getByRole('button',{name:'Remove shotla-audit.png',exact:true}).click();
  check(await page.getByTestId('text-layer').count() === 1, 'Removing active image selects remaining image with its state');
  await nav('Annotate'); await page.getByRole('button',{name:'Delete text 1',exact:true}).click(); await page.getByRole('button',{name:'Delete magnifier 1',exact:true}).click();
  check(await page.getByTestId('text-layer').count() === 0 && await page.getByTestId('magnifier').count() === 0, 'Layers can be deleted');
  await nav('Presets'); await page.getByRole('button',{name:'Delete Audit style style',exact:true}).click();
  await page.getByRole('button',{name:'Reset all styling',exact:true}).click();
  check(await canvasStyle('width') === '1260px', 'Reset restores fit and defaults');
  await page.screenshot({path:'output/playwright/redesign-desktop.png'});
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'Hide settings',exact:true}).click();
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth), 'Mobile layout has no horizontal overflow');
  await page.screenshot({path:'output/playwright/redesign-mobile.png'});
  for (const name of ['Images','Background','Canvas','Frame','Crop','Annotate','Export','Help','Presets']) {await nav(name); check(await page.getByRole('heading',{name,exact:true,level:1}).isVisible(), `Mobile ${name} panel opens`);}
  await page.screenshot({path:'output/playwright/redesign-mobile-sidebar.png'});
  await page.setViewportSize({width:1440,height:960});
  await nav('Presets');
  check(errors.length === 0, 'No runtime JavaScript errors during the audit');
  return {passed:results.length,results,errors};
}
